//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.31 at 07:26:46 AM MSK 
//


package com.geekbrains.spring.web.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productSOAP" type="{http://www.geekbrains.com/market}productSOAP"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productSOAP"
})
@XmlRootElement(name = "getProductResponse")
public class GetProductResponse {

    @XmlElement(required = true)
    protected ProductSOAP productSOAP;

    /**
     * Gets the value of the productSOAP property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSOAP }
     *     
     */
    public ProductSOAP getProductSOAP() {
        return productSOAP;
    }

    /**
     * Sets the value of the productSOAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSOAP }
     *     
     */
    public void setProductSOAP(ProductSOAP value) {
        this.productSOAP = value;
    }

}
